var translations = {
	proj: "projects",
	lab: "lab",
	about: "about",
	proj_description: "Designs that merge research, programming, art and data.",
	work: "↳ Work:",
	project_complete: "↳ Complete project:",
	contract_address: "↳ Contract address:",
	proj_header: "Projects.",
	gen_art: "Generative Art",
	vr: "VR Experience",
	inst: "Interactive Installation",
	web_app: "Web App",
	about_description: "Designer, Artist and Educator.",
	about_header: "I write images with computers.",
	bio_0:
		"Pedro Falco (1997) is an image and sound designer (UBA), artist and teacher. His work and research focus on the reinterpretation of data and the appropriation of the internet. Passionate about real-time processes, he explores generative systems, databases, blockchain technology and procedural modeling to create interactive installations, online experiences, electronic objects and data visualizations.",
	bio_1:
		"He has been part of exhibitions in Buenos Aires ('No existe tierra más allá' at CheLa, 'Arte Generativo y Criptoarte' at +CODE), Rio de Janeiro ('NFT Rio') and Bogota ('Exposición Datos + Arte' at Datasketch Gallery). He also held talks and seminars at the Cultural Center of Spain in Buenos Aires (CCEBA), Bafici and TRImarchi 20.",
	bio_2:
		'Since 2019 he has been teaching the subject "Audiovisual Theories" in the "Image and Sound Design" program at the University of Buenos Aires.',
	contact: "Feel free to write me for any question :)",
	asterisms_0:
		"An asterism is a collection of stars that, when one connects them mentally, they generate a pattern. Unlike constellations, they are a more general concept that can refer to any identified pattern of stars. The viewer is the one who draws in the sky and gives meaning to their creation.",
	asterisms_1:
		"'Asterisms' in an interactive generative project that invites you to draw, name and save forever your own asterism. Through a generative algorithm, the script gives you the sky as a canvas where you can unfold your imagination as many times as you want based on the Token ID hash from the minting process.",
	asterisms_2: "To be a user is to be a creator.",
	asterisms_3:
		"Instructions: LEFT CLICK to create stars │ Use the MOUSE WHEEL to zoom in and out │ TYPE to write a title │ BACKSPACE to delete text │ DELETE to delete all the text │ ENTER to save the file.",
	asterisms_4:
		"The project was launched on April 20, 2021 on the ArtBlocks platform, being one of the earliest projects to take advantage of blockchain technology and web programming to generate interactive experiences in real time.",
	asterisms_5:
		"My interest in this project lies precisely in exploring these new possibilities that Blockchain technology and the ArtBlocks platform enabled. At that time, the crypto ecosystem was debating whether the work was the image or the information that the token had. Within that context, it seemed interesting to me to generate a simple work (technically speaking) but that could allow me to talk about this and the problem of using rigid or inflexible categories.",
	asterisms_6:
		"As their name indicates, asterisms are groups of stars grouped together by the viewer and only make sense within their  context.",
	asterisms_7:
		"The project had a great reception by collectors who, after discovering how the interactivity worked, highlighted the poetics generated by the algorithm. Today the project consists of 100 iterations stored immutably on the Ethereum blockchain.",
	foliage_0:
		'"Foliage" is a moment of pause. The project was born from the futile attempt to catch a breath of wind, the one that no one sees but everyone notices when the leaves hang trembling. Inspired by long days near the Rio de la Plata studying the wind, this series of 250 foliage is an exploration of how angles and colors can generate the illusion of movement and harmony. "Foliage" is inspired on wind data visualizations where the use of angles and vectors speak of a trajectory. Winds, like data, travel through our world leaving a trace; this time hosted immutably on the Ethereum Blockchain.',
	foliage_1:
		'As I said, "Foliage" is inspired by the area where I grew up and lived most of my life. Very close to my house, a few blocks away, is the Río de la Plata, which is a very beautiful place, with lots of wind and vegetation. From that observation is that the project was born. That is why Foliage presents nine different types of plants and the name of each one is inspired by landscapes close to me.',
	foliage_2:
		"The category is called 'surface analysis' because when you study the winds you need to delimit a research area. In my case, these are my surfaces.",
	foliage_3:
		"Regarding the color palettes, I wanted there to be a wide variety of colors that could reflect many different moments of the year and many different moods.  In that variety, I decided to name the different color palettes following the names of the world's best known winds.",
	foliage_4:
		"To paint the foliage, I chose to use three techniques that I called: Random, Angle and Grid. Each uses a different technique that generates a different pattern. All the ways of coloring the foliage are based on the position and angle relationship that each leaf vector has.",
	foliage_5:
		'Each foliage can have different styles. I separated them into five different styles: Shady, Magic, Clean, Veins and Anime. The "Shady" style has more depth through shadow work that creates volume. In "Magic" the color palette is inverted to color the edges of the leaves, which makes it more vibrant and colorful.In the "Veins" style the border of the leaves can be black or white and this disappears as the leaves scale, while in "Clean" there is no border at all, which at times makes the colors lose their borders. The "Anime" style is quite different and alludes to something mystical.',
	foliage_6:
		"Finally, as the wind blows, the foliage may release more or less pollen, depending on their characteristics. There may be a lot or a light amount of pollen, or no pollen at all.",
	expulso_0:
		"The communication skeleton and its various devices are intended to some kind of response.",
	expulso_1: "Where do those words that wish not to be heard go?",
	expulso_2:
		"We live sunk at the bottom of an ocean of air that generates pressure on our bodies. Whoever wants to speak must have the opportunity to speak in a place with less pressure than atmospheric pressure, where the transmission of words in the air does not take place. It is necessary to take the pressure out of what surrounds us. By generating a vacuum, we can generate a decrease of the barometric pressure and thus reduce the real pressure we are talking about.",
	expulso_3:
		"This is why we feel the urgency to destroy the skeleton of communication. To eliminate the idea of sender-medium-receiver. By speaking into the void, we give way to the communication of what we understand as real and which, precisely in the world we live in, is destined to fail.",
	expulso_4:
		"In this way, a decrease in pressure gives rise to the poetics of silent words. A creation born of saying without pressure.",
	expulso_5: "For that, let us enjoy the fertility of emptiness.",
	expulso_6:
		"'EXPULSO' is an interactive installation that consists of a 4mts x 1.20mts x 2.40mts sheet metal room which invites the user to enter to expel. Once inside, the user goes through an airtight curtain and enters the sector where the pressure was decreased. \"What generates pressure for you?\" asks the room and the user must answer through a microphone hanging from the ceiling. While the sound of the words is canceled by the vacuum, the voice transmitted by the microphone causes a generative digital creature modified by the very characteristics of the user's speech to react.",
	expulso_7: "Each creature is unique and child of each person.",
	expulso_8:
		"Designed and produced by Clara Travieso, German Oriana, Abril Portillo, Octavio Castiñeira and Pedro Falco.",
	nube_0:
		"The Cloud is an interactive installation consisting of a small database which listens, stores and executes events that draw the sky as in a performance. The Cloud is an algorithm that seeks to think the behavior of clouds as a generative system.",
	nube_1:
		"However, the installation recalls its playful spirit and, through a graphic interface, invites users to play with the sky and alter the state of the weather while interacting with each other.",
	nube_2:
		"This project is a dialogue between two topics that I have been researching for several years: generative systems and the functioning of the Internet. The Cloud tries to generate a bridge between both universes and put them in dialogue.",
	nube_3:
		"The generation of images in real time is achieved through an algorithm that I developed in TouchDesigner, which listens to events that trigger different states such as the creation of clouds, thunder, rain, comets and data visualization, among others. It also has an internal clock that changes the sky depending on the local time.",
	nube_4:
		"On the other hand, the web interface communicates with TouchDesigner via Socket.IO and sends messages in real time through the Internet generating a fluid and latency-free communication between the users and the system.",
	boost_0:
		"Boost is an audiovisual piece that, through virtual reality, invites you to explore the under universe of car racing in Argentina.",
	boost_1:
		"Combining 360° recordings and 3D animation, the work oscillates between documentary and the sublimation of a state of ecstasy. For a few minutes, the viewer is immersed in a world devoid of pretentiousness, where there is just enough for the driver's condition to be repeated over and over again as the races go by. This eternal return allows the driver, even if only for 13 seconds, to have his moment of glory.",
	boost_2:
		"In this way, what appears to be a straight line with two cars is transformed into something much more complex where adrenaline, passion and senses combine to form a sacred ritual.",
	boost_3:
		'The piece was presented as a site-specific installation at the Avellaneda racetrack in 2018 and also in "La Noche de los Museos" in 2019.',
	boost_4:
		"Designed and realized by Juan Ignacio Migliardo, Abril Portillo, Harry Piluso Mulhall, Octavio Castiñeira and Pedro Falco.",
	meta_0:
		"Beyond what is given. Data about data. An audio spectrum visualization.",
	sr_sale:
		"Digitally generated image and processed in real-time. The work was tokenized on the Ethereum network with SuperRare contracts and is currently for sale.",
	sr_sold:
		"Digitally generated image processed in real-time. The work was tokenized on the Ethereum network with SuperRare contracts and is currently sold.",
	aurora_0:
		"Back wet. One night of solid silence he played his cards and dreams fled hopeless as sand. Ashes, blind equilibrist, getting lost in the air.",
	condensacion_nube_0:
		"Defined by themselves as a generative system, the clouds invite us to think about noise. Noise, like an image, is a moment. It's a challenge to get out of the noise without getting carried away by it. On the one hand, from the balcony, the things to do draw a hole. On the other, the parallels reveal the rational construction of the geoid system while the drops, obsequious, follow the agreed path. In a first approach to the cloud, politically correct considerations emerge: its morphology, digitized in its nature, lends itself to continuous change. At the risk of being wrong, it appears to be nothing more than information flowing camouflaged in red, green and blue containers, a high period and high harmonics. However, a change of state forces the viewer to a change of mood. It is obvious that what is seen always generates something, but the pseudo-randomness of the noise invites speculation as to what generates what it generates. Curled in its same ever-changing path, the observer finds respite in noise. It happens that noise does not seek to be decent. Nor does noise need any arrangement.",
	condensacion_nube_1:
		'"Observaciones sobre el ruido en la condensación de una nube" is a series guided by distress.',
	data_sculpture_0:
		"A data sculpture built from featured tweets mentioning ETH2.0. A document for posterity. Seamless loop 1920 x 1920 px.",
	drifting_0:
		"Drifting from a thought. Autonomous agents driven by rgb values.",
	ether_0:
		"A voyage through ether. The impossible will to taste what we couldn't live.",
	gray_matter_0:
		"Gray Matter is my first generative artwork. It's a continuous flow of data that drifts like a nervous system, leaving a trace, drawing a path. More than a million gray dots, invite us to see secret passages that thought takes to find new connections.",
	kinetic_sculpture_0:
		"Data flows from its skeleton. The construction is revealed. Place the body, place the text. The code as DNA, explains our erratic nature in movement. Live forever.",
	lockdown_0:
		"An attempt to look outward while forcing ourselves to look inward.",
	paranoia_0: "A new twisted journey through the mysteries of thought.",
	persistance_reality_0: "A fatal error during simulation.",
	pixel_bloom_0: "It's for you.-",
	promised_hesitate:
		"Doubt knocks on the door and the entire infinity breaks in.",
	rhizome_0:
		'"Make rhizomes, not roots, never plant! Don’t sow, grow offshoots! Don’t be one or multiple, be multiplicities! Run lines, never plot a point! Speed turns the point into a line! Be quick, even when standing still!"- Gilles Deleuze and Félix Guattari in Capitalism and Schizophrenia (1972–1980)',
	momentum_0:
		"Every drop of thought,	that you can't think, shake my bones. They slip out of my pockets.",
	author: "designed by Pedro Falco @ studio.falko",
	basura_0:
		"'Entre la basura' is a program to see what remains invisible among the spam I receive everyday.",
	basura_1:
		"The app works by connecting to the Google API to search for mails inside my spam folder. That material is used as a prompt to generate an image with DALL-E. For this, 'Entre la basura' connects to the OpenAi API and generates an image in real time.",
	rafagas_0:
		"Descripción: Ráfagas es una instalación interactiva que responde al movimiento de las personas que se acercan. Al moverse, lxs usuarixs, ejecutan un algoritmo que devuelve el rastro de esa ráfaga. La imagen resultante, inmóvil, es la creación de interesantes follajes arrastrados por el viento.",
	cookies:
		"The site was designed keeping your privacy in mind, with no cookies, advertising or requests of any kind. It only caches the images. The website is hosted @ netlify.com and open source @ github.com/pedrofalco 🤝",
};
